export default interface IMovieSubmit {
    title: string,
    originalTitle: string,
    tagline?: string,
    country: string,
    synopsis: string,
    genres: string[],
    staff: string[],
    cast: string[],
    releaseDate: string,
    runtime: number | "",
    originalLanguage: string,
    languages?: string[],
    subtitles?: string[],
    trailerURL?: string | null,
}